"""
3D Reel Studio — Services Package
Phase 4, Phase 5, Phase 6, Phase 7 & Phase 8: Storage, Audio, Transcription, Scene & Vision Analysis
"""

from app.services.storage import (
    get_base_storage_dir,
    get_project_storage_dir,
    validate_media_upload,
    generate_stored_filename,
    save_upload_file_chunked,
    delete_physical_file,
)
from app.services.audio import (
    get_project_audio_dir,
    resolve_ffmpeg_path,
    extract_audio_from_video,
)
from app.services.transcription import (
    get_openai_client,
    transcribe_audio_file,
    TranscriptionResult,
    SegmentData,
    WordTimestampData,
)
from app.services.analysis import (
    get_project_keyframes_dir,
    resolve_ffprobe_path,
    extract_video_metadata,
    detect_video_scenes,
    extract_keyframe_image,
    analyze_video_pipeline,
    VideoMetadata,
    SceneData,
    KeyframeData,
    AnalysisResult,
)
from app.services.vision import (
    detect_faces_in_image,
    estimate_body_pose,
    track_subjects_temporally,
    select_and_save_face_references,
    run_vision_analysis_pipeline,
    FacialLandmark,
    FaceDetectionResult,
    PoseLandmarkResult,
    PoseDetectionResult,
    DetectedSubjectResult,
    FaceReferenceResult,
    VisionAnalysisResult,
)
from app.services.comic_generation import (
    build_comic_generation_prompt,
    ComicGenerationProvider,
    OpenAIComicProvider,
    MockComicProvider,
    get_comic_generation_provider,
    run_comic_generation_pipeline,
    ComicGenerationServiceError,
)
from app.services.consistency import (
    select_canonical_and_multi_references,
    build_stable_character_descriptor,
    CharacterConsistencyService,
    run_consistency_generation_pipeline,
)
from app.services.segmentation import (
    SegmentationOutput,
    ForegroundSegmentationProvider,
    OpenCVSubjectGuidedSegmentationProvider,
    MockSegmentationProvider,
    get_segmentation_provider,
    refine_mask,
    reconstruct_clean_background,
    apply_background_mode,
    generate_composite_image,
    run_segmentation_pipeline,
)
from app.services.lyrics import (
    DEFAULT_LYRIC_STYLES,
    DEFAULT_LYRIC_ANIMATIONS,
    AnimationState,
    KineticTextEngine,
    ease_out_cubic,
    ease_out_back,
    ease_out_bounce,
    compute_animation_state,
    wrap_text_lines,
    composite_text_behind_character,
    get_or_create_default_styles,
    get_or_create_default_animations,
    sync_transcript_to_lyrics,
    generate_lyric_preview,
)
from app.services.render import (
    ReelCompositingEngine,
    run_final_reel_render_sync,
    cancel_render_job,
    resize_and_fit_916,
)
from app.services.maintenance import (
    reconcile_stale_jobs_on_startup,
    audit_project_storage,
    cleanup_project_storage,
)

__all__ = [
    "get_base_storage_dir",
    "get_project_storage_dir",
    "validate_media_upload",
    "generate_stored_filename",
    "save_upload_file_chunked",
    "delete_physical_file",
    "get_project_audio_dir",
    "resolve_ffmpeg_path",
    "extract_audio_from_video",
    "get_openai_client",
    "transcribe_audio_file",
    "TranscriptionResult",
    "SegmentData",
    "WordTimestampData",
    "get_project_keyframes_dir",
    "resolve_ffprobe_path",
    "extract_video_metadata",
    "detect_video_scenes",
    "extract_keyframe_image",
    "analyze_video_pipeline",
    "VideoMetadata",
    "SceneData",
    "KeyframeData",
    "AnalysisResult",
    "detect_faces_in_image",
    "estimate_body_pose",
    "track_subjects_temporally",
    "select_and_save_face_references",
    "run_vision_analysis_pipeline",
    "FacialLandmark",
    "FaceDetectionResult",
    "PoseLandmarkResult",
    "PoseDetectionResult",
    "DetectedSubjectResult",
    "FaceReferenceResult",
    "VisionAnalysisResult",
    "build_comic_generation_prompt",
    "ComicGenerationProvider",
    "OpenAIComicProvider",
    "MockComicProvider",
    "get_comic_generation_provider",
    "run_comic_generation_pipeline",
    "ComicGenerationServiceError",
    "select_canonical_and_multi_references",
    "build_stable_character_descriptor",
    "CharacterConsistencyService",
    "run_consistency_generation_pipeline",
    "SegmentationOutput",
    "ForegroundSegmentationProvider",
    "OpenCVSubjectGuidedSegmentationProvider",
    "MockSegmentationProvider",
    "get_segmentation_provider",
    "refine_mask",
    "reconstruct_clean_background",
    "apply_background_mode",
    "generate_composite_image",
    "run_segmentation_pipeline",
    "DEFAULT_LYRIC_STYLES",
    "DEFAULT_LYRIC_ANIMATIONS",
    "AnimationState",
    "KineticTextEngine",
    "ease_out_cubic",
    "ease_out_back",
    "ease_out_bounce",
    "compute_animation_state",
    "wrap_text_lines",
    "composite_text_behind_character",
    "get_or_create_default_styles",
    "get_or_create_default_animations",
    "sync_transcript_to_lyrics",
    "generate_lyric_preview",
    "ReelCompositingEngine",
    "run_final_reel_render_sync",
    "cancel_render_job",
    "resize_and_fit_916",
    "reconcile_stale_jobs_on_startup",
    "audit_project_storage",
    "cleanup_project_storage",
]



